query ConstructorStandingsPage($year: String!, $ref: String!) {
  constructorStandings(year: $year, ref: $ref) {
    id
    ref
    name
    nationality
    standings {
      round
      name
      date
      points
      position
      cumulativePoints
    }
  }
}
