env:
  browser: true
  node: true
  shared-node-browser: true
  es6: true
  jest: true
extends:
  - eslint:recommended
  - prettier
settings:
  react:
    version: detect
  import/resolver:
    typescript:
      project: tsconfig.json
rules:
  no-new-object: 2
  no-lonely-if: 2
