root: true
parser: '@typescript-eslint/parser'
root: true
parserOptions:
  ecmaVersion: 2020
  sourceType: module
  ecmaFeatures:
    jsx: true
    impliedStrict: true
  project: ./tsconfig.json
plugins:
  - '@typescript-eslint/eslint-plugin'
env:
  node: true
  es6: true
  browser: true
extends:
  - eslint:recommended
  - prettier
  - plugin:@typescript-eslint/recommended
rules:
  no-new-object: 2
  no-lonely-if: 2
  camelcase: 2
  no-console: 2
  no-unused-vars:
    - 2
    - vars: all
      args: after-used
      ignoreRestSiblings: true
