root: true
parserOptions:
  ecmaVersion: 2022
  sourceType: module
  ecmaFeatures:
    impliedStrict: true
env:
  node: true
  es6: true
extends:
  - eslint:recommended
  - prettier
rules:
  no-new-object: 2
  no-lonely-if: 2
  camelcase: 2
  no-console: 2

overrides:
  - files: src/_assets/scripts/*.js
    env:
      browser: true
    rules:
      no-console: 0
