root: true
parserOptions:
  ecmaVersion: 2020
  sourceType: module
  ecmaFeatures:
    jsx: true
    impliedStrict: true
env:
  node: true
  es6: true
  browser: true
extends:
  - eslint:recommended
  - prettier
rules:
  no-new-object: 2
  no-lonely-if: 2
  camelcase: 2
  no-console: 2
  no-restricted-imports: 0
  no-unused-vars:
    - 2
    - vars: all
      args: after-used
      ignoreRestSiblings: true
