parser: '@typescript-eslint/parser'
root: true
parserOptions:
  ecmaVersion: 2022
  sourceType: module
  ecmaFeatures:
    impliedStrict: true
  project: ./tsconfig.json
plugins:
  - '@typescript-eslint/eslint-plugin'
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - prettier
rules:
  no-new-object: 2
  no-lonely-if: 2
  no-unused-vars: 0

  '@typescript-eslint/no-use-before-define': 0
  '@typescript-eslint/explicit-function-return-type':
    - 1
    - allowExpressions: true
  '@typescript-eslint/no-unused-vars':
    - 2
    - vars: all
      args: after-used
      ignoreRestSiblings: true
      argsIgnorePattern: ^_
  '@typescript-eslint/no-shadow': 2
  '@typescript-eslint/no-duplicate-imports': 2
