env:
  node: true
  jest: true
  es2022: true
extends:
  - eslint:recommended
  - prettier
settings:
  react:
    version: detect
  import/resolver:
    typescript:
      project: tsconfig.json
rules:
  no-new-object: 2
  no-lonely-if: 2
