schema: src/server/graphql/schema.gql
documents: src/client/**/*.gql
extensions:
  endpoints:
    default:
      url: http://localhost:3000/graphql
  codegen:
    generates:
      ./src/server/graphql/types.ts:
        plugins:
          - typescript

      ./src/client/graphql/services.ts:
        plugins:
          - typescript
          - typescript-operations
          - typescript-urql
config:
  scalars:
    Date: string
  avoidOptionals:
    field: true
    inputValue: false
    object: true
    defaultValue: true
  skipTypename: true
  flattenGeneratedTypes: true
  namingConvention:
    enumValues: keep
