version: '3.8'
services:
  formula1-data:
    image: mariadb:10.8
    container_name: formula1-data
    ports:
      - '3306:3306'
    environment:
      MARIADB_DATABASE: f1db
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: yes
    volumes:
      - './temp:/docker-entrypoint-initdb.d'
