[build]
  publish = "public"
  command = "npm install -g pnpm && pnpm install --store=node_modules/.pnpm-store --frozen-lockfile && pnpm run build"

[build.environment]
  NPM_FLAGS="--version"
  NODE_VERSION="16"

[functions]
  directory = "src/_netlify/functions"
  # external_node_modules = ["mongodb"]
