openapi: '3.0.2'
info:
  title: Formula 1 App
  version: '1.0'
servers:
  - url: http://localhost:3000/api/rest
paths:
  /seasons/{year}/summary:
    get:
      summary: Get season summary for given year. Includes summary for constructors, drivers and races.
      operationId: getSeasonSummary
      parameters:
        - name: year
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Season summary for given year
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SeasonSummary'
  /seasons/{year}/constructors/{constructorRef}/standings:
    get:
      summary: Get standings for a constructor in a particular season
      operationId: getConstructorStandings
      parameters:
        - name: year
          in: path
          required: true
          schema:
            type: string
        - name: constructorRef
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Standings for a constructor in a particular season
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ConstructorSeasonStandings'
  /seasons/{year}/drivers/{driverRef}/standings:
    get:
      summary: Get standings for a driver in a particular season
      operationId: getDriverStandings
      parameters:
        - name: year
          in: path
          required: true
          schema:
            type: string
        - name: driverRef
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Standings for a driver in a particular season
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DriverSeasonStandings'
components:
  schemas:
    SeasonSummary:
      type: object
      required:
        - constructors
        - drivers
        - races
      properties:
        constructors:
          type: array
          items:
            type: object
            $ref: '#/components/schemas/ConstructorSeasonSummary'
        drivers:
          type: array
          items:
            type: object
            $ref: '#/components/schemas/DriverSeasonSummary'
        races:
          type: array
          items:
            type: object
            $ref: '#/components/schemas/RaceSeasonSummary'
    ConstructorSeasonSummary:
      type: object
      required:
        - constructor
        - points
        - position
      properties:
        constructor:
          type: object
          $ref: '#/components/schemas/Constructor'
        points:
          type: integer
        position:
          type: integer
    DriverSeasonSummary:
      type: object
      required:
        - driver
        - points
        - position
      properties:
        driver:
          type: object
          $ref: '#/components/schemas/Driver'
        points:
          type: integer
        position:
          type: integer
    Constructor:
      type: object
      required:
        - id
        - ref
        - name
        - nationality
        - url
      properties:
        id:
          type: integer
        ref:
          type: string
        name:
          type: string
        nationality:
          type: string
        url:
          type: string
    Driver:
      type: object
      required:
        - id
        - ref
        - forename
        - surname
        - nationality
        - url
        - dob
      properties:
        id:
          type: integer
        ref:
          type: string
        number:
          type: integer
          nullable: true
        code:
          type: string
          nullable: true
        forename:
          type: string
        surname:
          type: string
        nationality:
          type: string
        dob:
          type: string
        url:
          type: string
    RaceSeasonSummary:
      type: object
      required:
        - round
        - name
        - date
        - polePosition
        - winner
      properties:
        round:
          type: integer
        date:
          type: string
        name:
          type: string
        polePosition:
          type: object
          $ref: '#/components/schemas/Driver'
        winner:
          type: object
          $ref: '#/components/schemas/Driver'
    ConstructorSeasonStandings:
      allOf:
        - $ref: '#/components/schemas/Constructor'
        - type: object
          required: [standings]
          properties:
            standings:
              type: array
              items:
                $ref: '#/components/schemas/ConstructorRaceStanding'
    DriverSeasonStandings:
      allOf:
        - $ref: '#/components/schemas/Driver'
        - type: object
          required: [standings]
          properties:
            standings:
              type: array
              items:
                $ref: '#/components/schemas/DriverRaceStanding'
    ConstructorRaceStanding:
      type: object
      required:
        - round
        - name
        - date
        - circuit
        - city
        - country
        - cumulativePoints
        - position
        - points
      properties:
        round:
          type: integer
        name:
          type: string
        date:
          type: string
        circuit:
          type: string
        city:
          type: string
        country:
          type: string
        cumulativePoints:
          type: integer
        position:
          type: integer
        points:
          type: integer
    DriverRaceStanding:
      type: object
      required:
        - round
        - name
        - date
        - circuit
        - city
        - country
        - cumulativePoints
        - position
        - points
        - racePosition
      properties:
        round:
          type: integer
        name:
          type: string
        date:
          type: string
        circuit:
          type: string
        city:
          type: string
        country:
          type: string
        cumulativePoints:
          type: integer
        position:
          type: integer
          nullable: true
        points:
          type: integer
          nullable: true
        racePosition:
          type: integer
          nullable: true
