/* Generated by restful-react */

export const SPEC_VERSION = '1.0';
export interface SeasonSummary {
  constructors: ConstructorSeasonSummary[];
  drivers: DriverSeasonSummary[];
  races: RaceSeasonSummary[];
}

export interface ConstructorSeasonSummary {
  constructor: Constructor;
  points: number;
  position: number;
}

export interface DriverSeasonSummary {
  driver: Driver;
  points: number;
  position: number;
}

export interface Constructor {
  id: number;
  ref: string;
  name: string;
  nationality: string;
  url: string;
}

export interface Driver {
  id: number;
  ref: string;
  number?: number | null;
  code?: string | null;
  forename: string;
  surname: string;
  nationality: string;
  dob: string;
  url: string;
}

export interface RaceSeasonSummary {
  round: number;
  date: string;
  name: string;
  polePosition?: Driver;
  winner?: Driver;
}

export type ConstructorSeasonStandings = Constructor & {
  standings: ConstructorRaceStanding[];
};

export type DriverSeasonStandings = Driver & {
  standings: DriverRaceStanding[];
};

export interface ConstructorRaceStanding {
  round: number;
  name: string;
  date: string;
  circuit: string;
  city: string;
  country: string;
  cumulativePoints: number;
  position: number;
  points: number;
}

export interface DriverRaceStanding {
  round: number;
  name: string;
  date: string;
  circuit: string;
  city: string;
  country: string;
  cumulativePoints: number;
  position: number | null;
  points: number | null;
  racePosition: number | null;
}

export interface GetSeasonSummaryPathParams {
  year: string;
}

export interface GetConstructorStandingsPathParams {
  year: string;
  constructorRef: string;
}

export interface GetDriverStandingsPathParams {
  year: string;
  driverRef: string;
}
