/* Generated by restful-react */

export const SPEC_VERSION = '1.0.0';
export interface SeasonSummary {
  constructors: ConstructorSeasonSummary[];
  drivers: DriverSeasonSummary[];
  races: RaceSummary[];
}

export interface ConstructorSeasonSummary {
  constructor: Constructor;
  points: number;
  position: number;
}

export interface DriverSeasonSummary {
  driver: Driver;
  points: number;
  position: number;
}

export interface Constructor {
  id: number;
  ref: string;
  name: string;
  nationality: string;
  url: string;
}

export interface Driver {
  id: number;
  ref: string;
  number?: number | null;
  code?: string | null;
  forename: string;
  surname: string;
  nationality: string;
  dob: string;
  url: string;
}

export interface RaceSummary {
  round: number;
  date: string;
  name: string;
  polePosition: Driver;
  winner: Driver;
}

export interface SeasonSummaryPathParams {
  year: string;
}
