name: Main Branch Check
on:
  push:
    branches:
      - main
    paths:
      - 'src/**/*.*'
      - pnpm-lock.yaml
      - netlify.toml
      - .github/workflows/main.yaml
jobs:
  eslint:
    name: ESLint
    runs-on: ubuntu-latest
    steps:
      - name: Setup
        uses: vkbansal/pnpm-setup-action@v1
      - name: Lint
        run: pnpm run -r --if-present lint
  typecheck:
    name: TypeCheck
    runs-on: ubuntu-latest
    steps:
      - name: Setup
        uses: vkbansal/pnpm-setup-action@v1
      - name: Type Check
        run: pnpm run -r --if-present typecheck
  prettier:
    name: Prettier
    runs-on: ubuntu-latest
    steps:
      - name: Setup
        uses: vkbansal/pnpm-setup-action@v1
      - name: Prettier
        run: pnpm run -r --if-present fmtc
