name: 'Pull Request'
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
jobs:
  eslint:
    name: ESLint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'pnpm'
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          run_install: |
            - args: [--frozen-lockfile]
      - name: Lint
        run: |
          yarn
          yarn lint
  typecheck:
    name: TypeCheck
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'pnpm'
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          run_install: |
            - args: [--frozen-lockfile]
      - name: Type Check
        run: |
          yarn
          npx tsc --noEmit
  prettier:
    name: Prettier
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'pnpm'
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          run_install: |
            - args: [--frozen-lockfile]
      - name: Prettier
        run: |
          yarn
          yarn fmt:check
