name: 'Pull Request'
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
jobs:
  eslint:
    name: ESLint
    runs-on: ubuntu-latest
    steps:
      - name: Setup
        uses: './.github/workflows/setup-node.yaml'
      - name: Lint
        run: |
          yarn
          yarn lint
  typecheck:
    name: TypeCheck
    runs-on: ubuntu-latest
    steps:
      - name: Setup
        uses: './.github/workflows/setup-node.yaml'
      - name: Type Check
        run: |
          yarn
          npx tsc --noEmit
  prettier:
    name: Prettier
    runs-on: ubuntu-latest
    steps:
      - name: Setup
        uses: './.github/workflows/setup-node.yaml'
      - name: Prettier
        run: |
          yarn
          yarn fmt:check
