name: Update data
on: workflow_dispatch
jobs:
  update-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          token: '${{ secrets.GH_PAT }}'
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest
          run_install: false
      - name: Get pnpm store directory
        id: pnpm-cache
        run: |
          echo "pnpm_cache_dir=$(pnpm store path)" >> $GITHUB_ENV
      - name: Setup pnpm cache
        uses: actions/cache@v3
        with:
          path: ${{ env.pnpm_cache_dir }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-
      - name: Install dependencies
        run: pnpm install
      - name: Update data
        run: |
          set -e
          ./datagen/get-new-data.sh
      - name: Commit and Push
        uses: EndBug/add-and-commit@v9
        with:
          add: '.'
          author_name: 'Vivek Kumar Bansal'
          author_email: vkb0310@gmail.com
          message: 'chore: updated data (from GHA)'
          push: 'origin main --force'
