name: Update data
on: workflow_dispatch
jobs:
  update-data:
    runs-on: ubuntu-latest
    steps:
      - name: Setup
        uses: vkbansal/pnpm-setup-action@v1
      - name: Update data
        run: |
          set -e
          pnpm run data:up --datagen
      - name: Commit and Push
        uses: EndBug/add-and-commit@v9
        with:
          add: '.'
          author_name: 'Vivek Kumar Bansal'
          author_email: vkb0310@gmail.com
          message: 'chore: updated data (from GHA)'
          push: 'origin main --force'
